{
 "title": "Micrometer (CF)",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer",
  "cf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Org Name",
    "query": "label_values(system_cpu_count, org_name)"
   },
   {
    "name": "space_name",
    "label": "Space Name",
    "query": "label_values(system_cpu_count{org_name=\"$org_name\"}, space_name)"
   },
   {
    "name": "app_name",
    "label": "App Name",
    "query": "label_values(system_cpu_count{org_name=\"$org_name\", space_name=\"$space_name\"}, app_name)"
   },
   {
    "name": "cf_instance_id",
    "label": "CF Instance ID",
    "query": "label_values(system_cpu_count{org_name=\"$org_name\", space_name=\"$space_name\", app_name =\"$app_name\"}, cf_instance_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Uptime (Min)",
     "type": "singlestat",
     "description": "The uptime of the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(process_uptime_seconds{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})"
      }
     ]
    },
    {
     "title": "Process Start Time (Min)",
     "type": "singlestat",
     "description": "The starttime of the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "(time() - min(process_uptime_seconds{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})) * 1000"
      }
     ]
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Processor Count (Max)",
   "type": "singlestat",
   "description": "The number of processors available to the Java virtual machine",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(system_cpu_count{cf_instance_id=~\"$cf_instance_id\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Logback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trace log event",
     "type": "graph",
     "description": "Number of trace level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\", level=\"trace\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Debug log event",
     "type": "graph",
     "description": "Number of debug level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\", level=\"debug\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Info log event",
     "type": "graph",
     "description": "Number of info level events that made it to the logs",
     "gridPos": { "h": 8, "w": 6, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\", level=\"info\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Warn log event",
     "type": "graph",
     "description": "Number of warn level events that made it to the logs",
     "gridPos": { "h": 8, "w": 6, "x": 14, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\", level=\"warn\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Error log event",
     "type": "graph",
     "description": "Number of error level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\", level=\"error\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM Thread Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "JVM Threads Peak",
   "type": "graph",
   "description": "The peak live thread count since the Java virtual machine started or peak was reset",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Live Daemon Threads",
   "type": "graph",
   "description": "The current number of live daemon threads",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Live Total Threads",
   "type": "graph",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  { "title": "JVM Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Buffer Count",
   "type": "graph",
   "description": "An estimate of the number of buffers in the pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{id}}/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Buffer Mem Used",
   "type": "graph",
   "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{id}}/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Buffer Capacity",
   "type": "graph",
   "description": "An estimate of the total capacity of the buffers in this pool",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{id}}/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "graph",
   "description": "The maximum amount of memory in bytes that can be used for memory management",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{id}} ({{area}})/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "description": "The amount of used memory",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{id}} ({{area}})/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Committed Memory",
   "type": "graph",
   "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{id}} ({{area}})/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  { "title": "JVM Garbage Collection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Max Data Size",
   "type": "graph",
   "description": "Max size of old generation memory pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_max_data_size_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Live Data Size",
   "type": "graph",
   "description": "Size of old generation memory pool after a full GC",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Promoted Total",
   "type": "graph",
   "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Allocation Total",
   "type": "graph",
   "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Pause Count",
   "type": "graph",
   "description": "Time spent in GC pause",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_count{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{cause}} ({{action}})/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Pause Duration",
   "type": "graph",
   "description": "Time spent in GC pause",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_sum{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{cause}} ({{action}})/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  { "title": "Class Loader Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "description": "The number of classes that are currently loaded in the Java virtual machine",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "description": "The total number of classes unloaded since the Java virtual machine has started execution",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_unloaded_classes_total{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  { "title": "HTTP Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "HTTP Requests Count",
   "type": "graph",
   "description": "Count of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{method}} {{uri}} - {{status}}/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Max HTTP Requests Time",
   "type": "graph",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{method}} {{uri}} - {{status}}/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  }
 ]
}