{
 "title": "Micrometer: Overview",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer",
  "cf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(system_cpu_count, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(system_cpu_count{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "App Name",
    "query": "label_values(system_cpu_count{cluster=\"$cluster\", namespace=\"$namespace\"}, job)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(system_cpu_count{cluster=\"$cluster\", namespace=\"$namespace\", job =\"$job\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Uptime (Min)",
     "type": "singlestat",
     "description": "The uptime of the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(process_uptime_seconds{job=~\"$job\", pod=~\"$pod\"})"
      }
     ]
    },
    {
     "title": "Process Start Time (Min)",
     "type": "singlestat",
     "description": "The starttime of the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "(time() - min(process_uptime_seconds{job=~\"$job\", pod=~\"$pod\"})) * 1000"
      }
     ]
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Processor Count (Max)",
   "type": "singlestat",
   "description": "The number of processors available to the Java virtual machine",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(system_cpu_count{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{pod=~\"$pod\"}",
     "legendFormat": "{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{pod=~\"$pod\"}",
     "legendFormat": "{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Logback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trace log event",
     "type": "graph",
     "description": "Number of trace level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{job=~\"$job\", pod=~\"$pod\", level=\"trace\"}[1m])",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Debug log event",
     "type": "graph",
     "description": "Number of debug level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{job=~\"$job\", pod=~\"$pod\", level=\"debug\"}[1m])",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Info log event",
     "type": "graph",
     "description": "Number of info level events that made it to the logs",
     "gridPos": { "h": 8, "w": 6, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{job=~\"$job\", pod=~\"$pod\", level=\"info\"}[1m])",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Warn log event",
     "type": "graph",
     "description": "Number of warn level events that made it to the logs",
     "gridPos": { "h": 8, "w": 6, "x": 14, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{job=~\"$job\", pod=~\"$pod\", level=\"warn\"}[1m])",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Error log event",
     "type": "graph",
     "description": "Number of error level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{job=~\"$job\", pod=~\"$pod\", level=\"error\"}[1m])",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Thread Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "description": "The current number of  threads",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live_threads{job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "live/{{job}}/{{pod}}"
      },
      {
       "expr": "jvm_threads_daemon_threads{job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "daemon/{{job}}/{{pod}}"
      },
      {
       "expr": "jvm_threads_peak_threads{job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "peak/{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "{{state}}/{{job}}/{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Max Memory (Heap)",
   "type": "graph",
   "description": "The maximum amount of memory in bytes that can be used for memory management",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{job=~\"$job\", pod=~\"$pod\", area=\"heap\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Used Memory (Heap)",
   "type": "graph",
   "description": "The amount of used memory",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\", area=\"heap\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Committed Memory",
   "type": "graph",
   "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{job=~\"$job\", pod=~\"$pod\", area=\"heap\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Max Memory (Non Heap)",
   "type": "graph",
   "description": "The maximum amount of memory in bytes that can be used for memory management",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{job=~\"$job\", pod=~\"$pod\", area=\"nonheap\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Used Memory (Non Heap)",
   "type": "graph",
   "description": "The amount of used memory",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\", area=\"nonheap\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Committed Memory (Non Heap)",
   "type": "graph",
   "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{job=~\"$job\", pod=~\"$pod\", area=\"nonheap\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Buffer Count",
   "type": "graph",
   "description": "An estimate of the number of buffers in the pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Buffer Mem Used",
   "type": "graph",
   "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Buffer Capacity",
   "type": "graph",
   "description": "An estimate of the total capacity of the buffers in this pool",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity_bytes{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{id}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pause Rate",
     "type": "graph",
     "description": "Rate of GC",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{job=~\"$job\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})/{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Pause Duration",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{job=~\"$job\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})/{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Promotion Rate",
     "type": "graph",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{job=~\"$job\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Allocation Rate",
     "type": "graph",
     "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=~\"$job\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Class Loader Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "graph",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "description": "The total number of classes unloaded since the Java virtual machine has started execution",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_unloaded_classes_total{job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "{{job}}/{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "description": "Count of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=~\"$job\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{method}} {{uri}} - {{status}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Max HTTP Request Time",
   "type": "graph",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{method}} {{uri}} - {{status}}/{{job}}/{{pod}}"
    }
   ]
  },
  { "title": "HTTP Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "description": "Count of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count{job=~\"$job\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{method}} {{uri}} - {{status}}/{{job}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Max HTTP Request Time",
   "type": "graph",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds_max{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{method}} {{uri}} - {{status}}/{{job}}/{{pod}}"
    }
   ]
  }
 ]
}