name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      run: |
        set -e
        ./mvnw -V test
    - name: mvn package
      if: github.ref == 'refs/heads/master'
      run: |
        set -e
        ./mvnw -V package -Dmaven.test.skip=true
    - name: pack build
      if: github.ref == 'refs/heads/master'
      env:
        PACK_VERSION: 0.9.0
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        set -e
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        wget -q https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz
        tar xzf pack-*.tgz
        rm -f pack-*.tgz
        ./pack build making/demo-micrometer \
          -p target/demo-micrometer-*.jar  \
          --builder cloudfoundry/cnb:bionic \
          --publish
